// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcl8hrgaPj-fgVd2Vv01rqJcJ2RTsDUeU',
    appId: '1:918904685601:web:938e3d08109c8d1e998f60',
    messagingSenderId: '918904685601',
    projectId: 'health-recorder-3cc42',
    authDomain: 'health-recorder-3cc42.firebaseapp.com',
    storageBucket: 'health-recorder-3cc42.appspot.com',
    measurementId: 'G-XT1NED2K81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7iqPIEKsg1BQLTJkhYtGSHCPpMw2tbM',
    appId: '1:918904685601:android:030077a99f0c0647998f60',
    messagingSenderId: '918904685601',
    projectId: 'health-recorder-3cc42',
    storageBucket: 'health-recorder-3cc42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXTC74SlhT3ymF0wRXuRIVWec_DGWpPc',
    appId: '1:918904685601:ios:3a8083eb8d51d7b2998f60',
    messagingSenderId: '918904685601',
    projectId: 'health-recorder-3cc42',
    storageBucket: 'health-recorder-3cc42.appspot.com',
    iosBundleId: 'edu.seattleu.mobDev',
  );
}
